import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowDown, ArrowRight, ArrowUpRight, MapPin, Search } from 'lucide-react'
import { ReviewImage } from './HomePage'
import { phoneHref, serviceNames, units, unitSource } from './content'
import './site.css'

function Kicker({ children }: { children: React.ReactNode }) { return <span className="site-kicker">{children}</span> }
function ArrowLink({ to, children, external = false }: { to: string; children: React.ReactNode; external?: boolean }) {
  return external
    ? <a href={to} target="_blank" rel="noopener noreferrer" className="site-arrow-link">{children}<ArrowUpRight size={18} aria-hidden="true" /></a>
    : <Link to={to} className="site-arrow-link">{children}<ArrowUpRight size={18} aria-hidden="true" /></Link>
}

export function ServicesPage() {
  const [query, setQuery] = useState('')
  const matches = useMemo(() => serviceNames.filter(name => name.toLocaleLowerCase('pt-BR').includes(query.trim().toLocaleLowerCase('pt-BR'))), [query])
  return <div className="site-page">
    <section className="site-page-lead site-services-lead"><div className="site-width site-services-head"><div><Kicker>Walter’s / serviços</Kicker><h1>Um cuidado para cada <em>intenção.</em></h1></div><p>Do cabelo aos pequenos detalhes, encontre o cuidado que procura. A oferta pode variar conforme a unidade.</p></div><div className="site-width site-services-teaser"><span>O gesto muda.<br /><em>A atenção permanece.</em></span><figure><ReviewImage file="editorial-craft-generated-v2.png" alt="Imagem editorial ilustrativa de mãos trabalhando cabelo" /><figcaption>Imagem editorial ilustrativa</figcaption></figure></div></section>
    <section className="site-service-index" aria-labelledby="service-index-title"><div className="site-width"><div className="site-index-heading"><div><Kicker>Explore as possibilidades</Kicker><h2 id="service-index-title">Os cuidados</h2></div><label className="site-search"><Search size={19} aria-hidden="true" /><span className="sr-only">Buscar serviço</span><input value={query} onChange={event => setQuery(event.target.value)} type="search" placeholder="Buscar um cuidado" /></label></div><div className="site-service-list" aria-live="polite">{matches.length ? matches.map((name, index) => <div className="site-service-row" key={name}><span>{String(index + 1).padStart(2, '0')}</span><h3>{name}</h3><ArrowRight size={20} aria-hidden="true" /></div>) : <p className="site-empty">Nenhum cuidado encontrado. Tente outro termo.</p>}</div><p className="site-source-note">Categorias observadas no site Walter’s em 30/09/2026. Confirme serviço e disponibilidade na unidade escolhida.</p></div></section>
    <section className="site-decision"><div className="site-width site-decision-grid"><Kicker>Seu próximo passo</Kicker><h2>Escolha a unidade.<br /><em>Depois, o cuidado.</em></h2><div><p>Veja endereço e contato antes de agendar. Não exibimos horários ou vagas sem confirmação.</p><ArrowLink to="/unidades/">Encontrar unidade</ArrowLink></div></div></section>
  </div>
}

export function UnitsPage() {
  const [query, setQuery] = useState('')
  const matches = useMemo(() => {
    const term = query.trim().toLocaleLowerCase('pt-BR')
    return units.filter(unit => `${unit.name} ${unit.area} ${unit.address}`.toLocaleLowerCase('pt-BR').includes(term))
  }, [query])
  return <div className="site-page">
    <section className="site-units-lead"><div className="site-width"><Kicker>Walter’s / unidades</Kicker><h1>Encontre sua <em>Walter’s.</em></h1><p>Busque por bairro ou unidade. Confira o endereço e fale diretamente com o local escolhido.</p><a href="#unit-list" className="site-quiet-action">Explorar unidades <ArrowDown size={18} aria-hidden="true" /></a></div></section>
    <section id="unit-list" className="site-units-list"><div className="site-width"><div className="site-units-tools"><label className="site-search"><Search size={20} aria-hidden="true" /><span className="sr-only">Buscar unidade</span><input type="search" placeholder="Bairro, cidade ou nome da unidade" value={query} onChange={event => setQuery(event.target.value)} /></label><span aria-live="polite">{matches.length} {matches.length === 1 ? 'unidade encontrada' : 'unidades encontradas'}</span></div><div className="site-unit-rows">{matches.length ? matches.map((unit, index) => <article className="site-unit-row" key={unit.name}><span className="site-unit-index">{String(index + 1).padStart(2, '0')}</span><div><span className="site-unit-area">{unit.area}</span><h2>{unit.name}</h2><p><MapPin size={16} aria-hidden="true" />{unit.address}</p></div><div className="site-unit-links"><a href={phoneHref(unit.phone)} aria-label={`Ligar para ${unit.name}: ${unit.phone}`}>Ligar {unit.phone}</a><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${unit.name}, ${unit.address}, ${unit.area.startsWith('Niterói') ? 'Niterói' : 'Rio de Janeiro'}, RJ`)}`} target="_blank" rel="noopener noreferrer" aria-label={`Buscar endereço de ${unit.name} no Google Maps`}>Ver no mapa <ArrowUpRight size={16} aria-hidden="true" /></a></div></article>) : <p className="site-empty">Nenhuma unidade encontrada. Tente outro bairro ou nome.</p>}</div><p className="site-source-note">Endereços e telefones transcritos da <a href={unitSource} target="_blank" rel="noopener noreferrer">lista publicada pela Walter’s</a>, consultada em 30/09/2026. Antes da visita, confirme horário, serviços e contato com a unidade. Não exibimos vagas em tempo real.</p></div></section>
  </div>
}

export function AboutPage() {
  return <div className="site-page"><section className="site-about-lead"><div className="site-width site-about-grid"><div><Kicker>Walter’s / a marca</Kicker><h1>Uma história feita de cabelo <em>e pessoas.</em></h1><p>A marca leva o nome de Walter Cabral. O interesse pelo ofício e pelo aprendizado atravessa a história que chegou aos salões Walter’s.</p></div><figure><ReviewImage file="editorial-hero-generated-v2.png" alt="Retrato editorial ilustrativo com foco no cabelo e no rosto" /><figcaption>Imagem editorial ilustrativa</figcaption></figure></div></section><section className="site-about-story"><div className="site-width site-about-story-grid"><Kicker>O início</Kicker><div><h2>Um ofício que se constrói <em>com o tempo.</em></h2><p>Walter Cabral começou a trabalhar com cabelo ainda jovem e continuou estudando corte e penteado ao longo da carreira. Essa relação entre prática e aprendizado segue como fio da narrativa da marca.</p><ArrowLink to="/academy/">Conhecer a Academy</ArrowLink></div></div></section><section className="site-brand-paths"><div className="site-width"><Kicker>Mais de um caminho</Kicker><div><Link to="/academy/">Academy <ArrowUpRight aria-hidden="true" /></Link><Link to="/barbeariawalters/">Barbearia Walter’s <ArrowUpRight aria-hidden="true" /></Link><Link to="/concept/">Concept <ArrowUpRight aria-hidden="true" /></Link></div></div></section></div>
}

export function AcademyPage() {
  return <div className="site-page"><section className="site-academy-lead"><div className="site-width site-academy-grid"><div><Kicker>Walter’s / formação</Kicker><h1>Aprender também é <em>transformar.</em></h1><p>Um espaço para começar, praticar e ampliar o repertório no universo da beleza.</p><ArrowLink to="https://waltercoiffeur.com.br/academy/" external>Consultar a Academy no site atual</ArrowLink></div><figure><img src="/editorial-2026/academy-v2.jpg" alt="Cena conceitual de formação prática em beleza" /><figcaption>Imagem editorial conceitual</figcaption></figure></div></section><section className="site-academy-fields"><div className="site-width"><Kicker>Áreas de formação</Kicker><h2>Um percurso próprio <em>para cada técnica.</em></h2><div className="site-fields-grid"><span>Corte e escova</span><span>Cor e mechas</span><span>Barbearia</span><span>Maquiagem e unhas</span></div><p>Áreas mencionadas no site da Academy. Consulte a equipe para saber turmas, requisitos e valores atuais.</p></div></section></div>
}

export function BarbershopPage() {
  return <div className="site-page"><section className="site-barber-lead"><div className="site-width site-barber-grid"><div><Kicker>Walter’s / barbearia</Kicker><h1>Outro ritual.<br /><em>O mesmo cuidado.</em></h1><p>Cabelo, barba e atenção aos detalhes em um universo próprio da Walter’s.</p><ArrowLink to="/unidades/">Encontrar uma unidade</ArrowLink></div><figure><img src="/editorial-2026/barbershop-v2.jpg" alt="Barbeiro cuidando da barba de um homem em imagem conceitual" /><figcaption>Imagem editorial conceitual</figcaption></figure></div></section><section className="site-barber-note"><div className="site-width"><span>01 / cabelo</span><span>02 / barba</span><span>03 / seu tempo</span></div></section><section className="site-subpage-end"><div className="site-width"><Kicker>Antes de ir</Kicker><h2>O melhor caminho é <em>a unidade certa.</em></h2><p>Consulte o endereço e confirme os cuidados oferecidos diretamente com a unidade.</p><ArrowLink to="/unidades/">Ver unidades</ArrowLink></div></section></div>
}

export function ConceptPage() {
  return <div className="site-page"><section className="site-concept-lead"><div className="site-width site-concept-grid"><div><Kicker>Walter’s / concept</Kicker><h1>Um espaço para sentir a beleza <em>de outro jeito.</em></h1><p>O Concept é um formato de salão da Walter’s que combina atendimento personalizado, inovação, elegância e atenção à sustentabilidade. Consulte os endereços e confirme os serviços diretamente com a unidade.</p><ArrowLink to="/unidades/">Ver todas as unidades</ArrowLink></div><figure><img src="/editorial-2026/concept-v2.jpg" alt="Representação conceitual de um salão contemporâneo" /><figcaption>Imagem conceitual; não representa uma unidade real</figcaption></figure></div></section><section className="site-concept-bridge"><div className="site-width"><p>Uma identidade.<br /><em>Novas perspectivas.</em></p><span>Imagem, espaço e cuidado em diálogo.</span></div></section></div>
}

export function FranchisePage() {
  return <div className="site-page site-franchise">
    <section className="site-franchise-lead" aria-labelledby="franchise-title">
      <div className="site-width site-franchise-hero-grid"><div className="site-franchise-hero-copy"><Kicker>Walter’s / franquias</Kicker><h1 id="franchise-title">Uma história para <em>construir a próxima.</em></h1><p>Empreender no universo da beleza é unir visão de negócio, pessoas e cuidado. Conheça os pilares que a Walter’s apresenta para quem deseja fazer parte da rede.</p><a className="site-arrow-link" href="#franchise-approach">Explorar a proposta <ArrowDown size={18} aria-hidden="true" /></a></div><figure className="site-franchise-hero-image"><img src="/editorial-2026/concept-v2.jpg" alt="Representação conceitual de um espaço de salão contemporâneo" /><figcaption>Imagem conceitual; não representa uma unidade real</figcaption></figure></div>
      <div className="site-width site-franchise-hero-footer" aria-hidden="true"><span>Marca</span><span>Formação</span><span>Operação</span></div>
    </section>
    <section id="franchise-approach" className="site-franchise-approach" aria-labelledby="franchise-approach-title"><div className="site-width"><div className="site-franchise-approach-head"><Kicker>O que a rede apresenta</Kicker><h2 id="franchise-approach-title">Mais que um endereço. <em>Uma estrutura por trás.</em></h2><p>Na apresentação oficial de franquias, a Walter’s destaca frentes de apoio que conectam marca, qualificação, comunicação e gestão. O escopo atual de cada frente deve ser confirmado diretamente com a rede.</p></div><div className="site-franchise-pillars"><article><span>01 / Identidade</span><h3>Uma marca<br />reconhecível.</h3><p>A rede destaca sua trajetória no mercado de beleza e sua presença em mídia como parte da proposta para franqueados.</p></article><article><span>02 / Pessoas</span><h3>Formação que<br />segue junto.</h3><p>A Walter’s Academy aparece na proposta como frente de formação e qualificação profissional.</p></article><article><span>03 / Presença</span><h3>Comunicação<br />em movimento.</h3><p>Marketing, redes sociais e assessoria de imprensa estão entre as iniciativas descritas no material oficial.</p></article><article><span>04 / Rotina</span><h3>Apoio para<br />operar.</h3><p>A página da rede também menciona supervisão de campo, sistema de gestão, inovação digital e parcerias.</p></article></div></div></section>
    <section className="site-franchise-training" aria-labelledby="franchise-training-title"><figure><img src="/editorial-2026/academy-v2.jpg" alt="Cena editorial conceitual de formação prática de profissionais da beleza" loading="lazy" /><figcaption>Imagem editorial conceitual</figcaption></figure><div className="site-franchise-training-copy"><div><Kicker>Walter’s Academy</Kicker><h2 id="franchise-training-title">Um negócio também se faz <em>de gente preparada.</em></h2><p>O cuidado vivido no salão começa com quem o oferece. Por isso, a formação ocupa um lugar próprio na apresentação de franquias da marca.</p><ArrowLink to="/academy/">Conhecer a Academy</ArrowLink></div></div></section>
    <section className="site-franchise-next" aria-labelledby="franchise-next-title"><div className="site-width site-franchise-next-grid"><div><Kicker>O próximo passo</Kicker><h2 id="franchise-next-title">Os detalhes certos começam <em>com uma conversa.</em></h2></div><div><p>Investimento, taxas, requisitos e prazos precisam vir de uma proposta atualizada. Esta amostra não reproduz estimativas publicadas anteriormente como se ainda estivessem vigentes.</p><ArrowLink to="https://waltercoiffeur.com.br/sejanossofranqueado/" external>Consultar a proposta oficial</ArrowLink><a className="site-franchise-email" href="mailto:relacionamento@waltercoiffeur.com.br?subject=Interesse%20em%20franquia%20Walter%27s">Escrever para a Walter’s <ArrowUpRight size={16} aria-hidden="true" /></a></div></div><p className="site-width site-source-note">Informações institucionais baseadas na <a href="https://waltercoiffeur.com.br/sejanossofranqueado/" target="_blank" rel="noopener noreferrer">página oficial de franquias</a>, consultada em 02/10/2026. Condições comerciais e disponibilidade devem ser confirmadas com a rede.</p></section>
  </div>
}
